sudo: false
language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - "$HOME/.cache"

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  slack:
    secure: PiVaV8GrPtIGKQZ+YtyKTakyVLuHGtMhn+6qi0IL3jj3L9g6OpJLp3hDXIx4x/mTdaG7TiOzg6shgMkDT0kvRYZChJBxOZsZcCCD7OWrBOy3gUOBD29V//HrnuzAdjElGbkvpx9j7fHoIZwROwV7iHL6i8URbBuQbohPJcMnHgWed70nNiY+d4DJgGaxepAcajwhjjAXlrEuzPQpoQi6cQaa2oA2762Okw7E4rZgM2lWfSXTYTwMuYlvlkY6WbE1Vx0AAMnY+hVDBrzdpGg3GaIJlaM9QQn21/3pHpRgLpBvryZ1DwURRVitDHI/LSBhvUNejq3K6dQxFQTJKQWN+ydHjSJKP4Ojb2rsx7JKj4yMgtyssBcx6W+elGPt3pxx7Ouh+zJ0eu9s1YhbJNH4+SioC/tTLD1dRGRXZruu/HImRxtcMi5mU8x836uz3uqzlzuMBzNmUuLUK54ATAn9Fb4qgjhRkhnpG8NmrmP1VyIKlFG3FNFe6FKr7/O0vL73Kx+n0Wm3iEO2MoDwrnVe5PshxdAWOrRmTxZyNQ+Ez85qyamNFGCAtCo42nL0hkJyX9mraXqi3/t8RG8P5ZInatq6oh8a2jHt/ssknhi9GRhR+2WSDvOS5XaQUVnfcx3kwKSysh9Lc45s89WCNe39bWyOCta94Ldhjt7Y+AKsFLM=
